In [1]:
import pandas as pd
import yfinance as yf
df = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies', attrs = {'id': 'constituents'})
data = yf.download(" ".join(df[0]['Symbol']))

[*********************100%***********************]  505 of 505 completed

2 Failed downloads:
- BRK.B: No data found, symbol may be delisted
- BF.B: 1d data not available for startTime=-2208988800 and endTime=1634496300. Only 100 years worth of day granularity data are allowed to be fetched per request.

In [14]:
data['Adj Close']

,A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,...,XEL,XLNX,XOM,XRAY,XYL,YUM,ZBH,ZBRA,ZION,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
1962-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.103276,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.104810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.105065,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.102765,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.102509,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-11,150.020004,20.129999,212.119995,142.809998,109.018311,122.400002,332.149994,116.430458,325.533539,573.070007,...,62.439999,155.199997,61.560001,57.169998,118.790001,122.000000,143.789993,493.130005,62.439999,197.649994
2021-10-12,147.949997,20.290001,212.009995,141.509995,107.269516,119.730003,334.140015,116.868767,326.720001,580.690002,...,63.000000,155.910004,61.240002,56.910000,118.760002,122.360001,142.809998,494.540009,62.709999,197.149994
2021-10-13,150.220001,19.610001,210.320007,140.910004,107.229996,118.839996,336.049988,116.549995,330.179993,591.119995,...,64.389999,161.649994,61.070000,56.230000,119.940002,123.519997,142.770004,496.859985,62.139999,197.460007
2021-10-14,152.589996,19.639999,214.860001,143.759995,108.910004,120.110001,345.070007,117.570000,339.040009,607.510010,...,65.430000,165.809998,62.000000,56.950001,123.370003,125.050003,145.630005,511.350006,62.639999,200.389999
2021-10-15,153.270004,19.980000,215.429993,144.839996,109.330002,119.860001,351.369995,117.489998,341.820007,610.090027,...,65.930000,167.149994,62.590000,57.849998,124.690002,125.209999,146.360001,515.830017,62.139999,202.220001